//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectsSchedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubjectsSchedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;h2&gt;Shema rasporeda&lt;/h2&gt;
        ///        &lt;p&gt;
        ///            Sada vidite tabelu koja prikazuje shemu rasporeda. Možete kliknuti na svaku učionicu ispod datuma
        ///            da odete na pregled termina u toj učionici.
        ///        &lt;/p&gt;
        ///
        ///        &lt;p&gt;
        ///            Nazad na &lt;a href=&quot;Indeks.htm&quot;&gt;indeks&lt;/a&gt; pomoći.
        ///        &lt;/p&gt;
        ///
        ///    &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string CitavRaspored {
            get {
                return ResourceManager.GetString("CitavRaspored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;STRANICA NIJE PRONAĐENA&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;h1&gt;Tražena stranica nije pronađena&lt;/h1&gt;
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;
        ///        Pomoć pri popunjavanju forme
        ///    &lt;/h2&gt;
        ///    &lt;p&gt;
        ///        &lt;b&gt;Identifikator&lt;/b&gt; - niz karaktera koji jedinstveno identifikuje jedan entitet.
        ///        Identifikator ne smije imati više od 4 ni manje od 1 karaktera i mora biti jedinstven u cijelom sistemu.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &lt;b&gt;Opis&lt;/b&gt; - tekstualni opis jedne učionice. Ovdje možete uni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Forma {
            get {
                return ResourceManager.GetString("Forma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap graph2 {
            get {
                object obj = ResourceManager.GetObject("graph2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt; Raspored v1.0 | Podrazumevana stranica pomoći &lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Podrazumevana stranica pomoći&lt;/h2&gt;
        ///    &lt;div&gt;
        ///        &lt;p&gt;
        ///            Ne postoji konkretan sadržaj pomoći za traženi dio aplikacije.
        ///            Molimo pogledajte &lt;b&gt;Indeks&lt;/b&gt; pomoći, u kome
        ///            se nalaze linkovi ka svim pojmovima za koje pomoć postoji.
        ///        &lt;/p&gt;
        ///    &lt;/div&gt;
        ///
        ///    &lt;h3&gt;Indeks&lt;/h3&gt;
        ///    &lt;p&gt;
        ///        U nas [rest of string was truncated]&quot;;.
        /// </summary>
        public static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap oneClassroom {
            get {
                object obj = ResourceManager.GetObject("oneClassroom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Raspored jedne učionice&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        Sada vidite tabelu koja prikazuje raspored termina u jednoj učionici. Sa lijeve strane Vam se nalazi spisak
        ///        predmeta (njihovih termina) koji mogu biti dodati u ovu učionicu.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Da dodate jedan termin nekog predmeta za neki dan u ovoj učionici, uradite sljedeće:
        ///        &lt;o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RasporedJedneUcionice {
            get {
                return ResourceManager.GetString("RasporedJedneUcionice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Tabela učionica&lt;/h2&gt;
        ///    &lt;p&gt;
        ///        Sada vidite tabelu koja prikazuje sve učionice koje su trenutno u sistemu. O svakoj učionici su prikazani
        ///        samo osnovni detalji koji pomažu u jedinstvenoj identifikaciji učionice. Ovdje možete dodavati nove učionice,
        ///        uklanjati postojeće ili pogledati detaljan opis svake učionice.
        ///    &lt;/p&gt;
        ///    &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TabelaClassroom {
            get {
                return ResourceManager.GetString("TabelaClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TestApiWpf {
            get {
                object obj = ResourceManager.GetObject("TestApiWpf", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
